language: python
install:
  - pip install tox
dist: xenial
python: 3.5  # Use the oldest supported version of python as default.
script:
    - tox -e $TOX_ENV
matrix:
  include:
    # TEST DOCS AND LINTING
    # Use default python3 version here.
    - env: TOX_ENV=py3-docs
    - env: TOX_ENV=py3-lint

    # UNIT TESTS
    # On most recent versions of python.
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.5
      env: TOX_ENV=py35
      install:
        - pip install codacy-coverage
        - pip install codecov
        - pip install tox
      after_success:
        # Correct coverage xml for coverage services.
        - >
          bash -c 'set -eux;
          pkg_path=$(find .tox/py*/lib/python*/site-packages/fastqsplitter -maxdepth 0 -type d);
          sed -i "s:${pkg_path}:src/fastqsplitter:g" coverage.xml'
        - codecov -v  # -v to make sure coverage upload works.
