comment: off
coverage:
  status:
    project:
      default:
        target: 90  # let's try to hit high standards
    patch:
      default:
        target: 90  # Tests should be written for new features
